### PR TITLE
Fix framework bundle version constraint to allow 3.0

### PR DESCRIPTION
**Pull request by adrienbrault**
The `~2.2` won't let me install 3.0

### CODE REVIEW

**Comment by xabbuh** [comment]
I suggest not to do that yet. Once this change get released, you are stating that the GuzzleBundle will be compatible with Symfony 3.x. However, you would not be able to revert that later (it would mean a BC break) when you discovered that a BC breaking change in FrameworkBundle 3.0 is incompatible with the GuzzleBundle (there will be no stable version of Symfony 3.0 before the end of the year).

**Comment by adrienbrault** [comment]
Right, that's wrong. For some reason without this I was not able to update `sensio/framework-extra-bundle` to the 3.0 version (which is still symfony 2)

**Comment by xabbuh** [comment]
@adrienbrault Would you mind showing a `composer.json` file that leads to unresolvable requirements?

**Comment by adrienbrault** [comment]
```
"sensio/framework-extra-bundle": "dev-master#98871b3397e258dd9d16d65023268e6baa0202cf as 3.0.8",
"misd/guzzle-bundle": "1.1.*",
```

```
$ composer update sensio/framework-extra-bundle
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sensio/framework-extra-bundle dev-master conflicts with misd/guzzle-bundle[v1.1.5].
    - sensio/framework-extra-bundle dev-master conflicts with misd/guzzle-bundle[v1.1.5].
    - sensio/framework-extra-bundle dev-master conflicts with misd/guzzle-bundle[v1.1.5].
    - Installation request for sensio/framework-extra-bundle dev-master#98871b3397e258dd9d16d65023268e6baa0202cf as 3.0.8 -> satisfiable by sensio/framework-extra-bundle[dev-master].
    - Installation request for misd/guzzle-bundle == 1.1.5.0 -> satisfiable by misd/guzzle-bundle[v1.1.5].
```

**Pull request closed without merging**
